# Generated by Django 2.1.1 on 2018-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
